# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<oss@fastly.com>"]
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "javascript"
manifest_version = 3
name = "looproxy"


[scripts]
  build = "npm run build"
  post_init = "npm install"


[setup]

  [setup.backends]

    [setup.backends.origin]
      address = "httpbin.org"
      description = "A basic real-time chat app, with API-key authentication, running on Glitch."
      port = 443
