# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<oss@fastly.com>"]
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "javascript"
manifest_version = 3
name = "Default starter for JavaScript"

[scripts]
build = "npm run build"
post_init = "npm install"

[setup.backends."api.openweathermap.org"]
description = "OpenWeatherMap API Server"
address = "api.openweathermap.org"
port = 443

[setup.config_stores."weather_auth".items.key]
description = "API token for openweathermap.org"
input_type = "string" 
